### ISSUE TITLE
Cancel observe-k8s WG meetings

### ISSUE THREAD

**Issue by kenfinnigan** [cncf/tag-observability#157]
Please cancel the currently scheduled observe-k8s WG meetings for Dec 20th and Jan 3rd

**Comment by halcyondude** [comment]
Created https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-2088

![image](https://github.com/cncf/tag-observability/assets/3286990/dcf650ed-570a-4065-956d-1859039aa4d0)

**Comment by alolita** [comment]
@kenfinnigan I tried to delete the events from the CNCF Community calendar but we don't have access to delete events on this calendar -  CNCF Community Meetings Created by: swilliams@linuxfoundation.org

@halcyondude Thanks for opening up a service desk ticket.

**Comment by halcyondude** [comment]
They've responded, meetings have been removed, which I've confirmed.
