### ISSUE TITLE
Proposal to expand Observability TAG meeting for CNCF APAC community

### ISSUE THREAD

**Issue by alolita** [cncf/tag-observability#181]
Cloud native observability adoption and open source innovation continues to grow at a rapid pace in APAC. There are multiple end-users as well as cloud providers in Asia who are contributing to CNCF observability projects including OpenTelemetry. 

We are excited that some of our APAC community members have requested that the CNCF Observability TAG consider holding a regular TAG meeting on APAC friendly times. @ralf0131 and team have also offered to host the online meeting.

Following up on this request, I propose the Observability TAG in collaboration with the APAC observability community holds one meeting a month at a APAC friendly time. We would like to kickstart this series this month starting next Tuesday July 9 PT / Wednesday July 10 morning APAC time.

The proposed times are:
1.  5-6pm PT on the second Tuesday each month which is 9-10am (UTC+8 hours) or
2. 6-7pm PT on the second Tuesday each month which is 10-11am (UTC+8 hours) 

Please vote to express your interest in joining the APAC friendly meeting with a thumbs up. 

Also, please express your preferred time option (1) or (2) in the comments below.

**Comment by ralf0131** [comment]
Big thanks for @alolita for making it happen! I believe with the regular meeting occurring in APAC friendly time, there are many more users and contributors can have a chance to communicate with the Observability TAG.

My preferable time is:

- [x] 5-6pm PT on the second Tuesday each month which is 9-10am (UTC+8 hours) or

I'd like to take the host responsibility but I do not know the rules :)

**Comment by alolita** [comment]
@ralf0131 Thanks for offering to host the APAC meeting - I will Slack you to discuss details. 

A couple of things - please add all meeting notes (agenda topics, attendees, links) to the Observability TAG meeting notes doc (attached in the calendar invite). The second is that the CNCF Code of Conduct applies to all participating in the meeting. See https://github.com/cncf/foundation/blob/master/code-of-conduct.md

**Comment by ralf0131** [comment]
There is an ongoing discussion on the OTel project around Asia Pacific friendly time raised by @codefromthecrypt as well. https://github.com/open-telemetry/community/issues/2176

**Comment by codefromthecrypt** [comment]
thanks for the connect and nice to see this sentiment going!

One idea in the other issue was for 8am GMT+8. This is a little early for folks in singapore, hong kong, perth, etc, but not in a damaging way. It may interrupt lunch in new zealand, too, but it does allow people in pacific timezone to join during working hours (4pm). The idea is that while this region is growing, we'd be better off at least at first with an easy to attend meeting for west coast US, vancouver etc,

personally speaking, later is fine with me and if 8am is not available 9 or 10am doesn't matter either.

**Comment by drewby** [comment]
Hi @alolita, I'm willing to help with this also. I am in Japan and can help @ralf0131 with hosting, presenting topics, and/or other organizational needs.

**Comment by alolita** [comment]
That's awesome @drewby Thank you! We plan to have our first TAG meeting next week on Tuesday July 9 PT / Wednesday July 10 APAC time. Do you have a time preference - Japan time will be 10-11am July 10.

**Comment by drewby** [comment]
That time will work for me. Thanks!

**Comment by ralf0131** [comment]
Hi, 

As is closed to the next meeting time, I wonder whether this proposal has been approved or not. I also want to know how to get access to the meeting. I checked `https://www.cncf.io/calendar/` but I can't find it.

**Comment by alolita** [comment]
Hi @ralf0131 this proposed time for the Observability TAG APAC meeting is accepted by everyone participating on this thread. Lets start with this time and then based on community participation can adjust later if needed. See everyone tomorrow at 5-6pm PT on the second Tuesday each month which is 9-10am (UTC+8 hours).

**Comment by ralf0131** [comment]
Hi, @alolita 

Thanks for the update. My next question is how can I find the link to join the meeting?

**Comment by alolita** [comment]
Huxing @ralf0131 I have requested CNCF for a new calendar event to be added to the CNCF community meetings calendar. In case the event is not created in the next few hours, we can use the standard zoom call info for the Observability TAG APAC meeting tomorrow - The call info can be found in the meeting notes at https://docs.google.com/document/d/1_QoF-njScSuGFI3Ge5zu-G8SbL6scQ8AzT1hq57bRoQ/edit

**Comment by ralf0131** [comment]
Hi @alolita ,

I have difficulties joining the zoom meeting. I found the meeting [link](https://zoom.us/j/91486841153?pwd=TmxaczdPWXNna1BISDhLOVY0VjFidz09) in the [meeting notes](https://docs.google.com/document/d/1_QoF-njScSuGFI3Ge5zu-G8SbL6scQ8AzT1hq57bRoQ/edit), however it requires login to join the meeting. Due to the limitation in China we cannot login to zoom to join this meeting :(. Is it possible to set up a meeting without requirement to login?  As a reference, the Java instrumentation bi-weekly meeting does not requires login to join the meeting.

**Comment by alolita** [comment]
@ralf0131 the calendar event is now set up on the CNCF community meeting calendar. 

You should be able to join into the meeting without logging in - I found these instructions on the Zoom site - https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0059553#:~:text=You%20do%20not%20need%20a,signing%20in%20to%20an%20account.
Let me know if this works.

**Comment by alolita** [comment]
@ralf0131 quick update: folks should be able to join the meeting without any login requirements! See you at the meeting.

**Comment by alolita** [comment]
Folks - if you are joining in for the APAC meeting today - its at 6-7pm PT. Please use the Google meet link listed in the doc for the meeting. See you then!

**Comment by ralf0131** [comment]
Hi All,

The next TAG meeting will be held on Tuesday Aug 13 PT / Wednesday Aug 14 APAC time. 
If you have any topics to share please update the [doc](https://docs.google.com/document/d/1_QoF-njScSuGFI3Ge5zu-G8SbL6scQ8AzT1hq57bRoQ/edit).

**Comment by kenfinnigan** [comment]
@alolita would you agree this issue can be closed, as we're now having regular APAC time friendly meetings?

**Comment by alolita** [comment]
@kenfinnigan Agreed. Closing this issue as completed.
