### ISSUE TITLE
Perses Project Review for TOC

### ISSUE THREAD

**Issue by alolita** [cncf/tag-observability#188]
The Observability TAG has been requested to provide a technical review of Perses for the TOC Sandbox Review process. 

For reference see https://github.com/cncf/sandbox/issues/134 and https://github.com/cncf/sandbox/issues/93

TAG Review can be found at - https://docs.google.com/document/d/1WaE9OSJKUm8nIX81KN5cNnnedXx6NDJ8iKE-zyzVPTw/edit#heading=h.gyyp2gtmqnww

**Comment by bwplotka** [comment]
ack

**Comment by manolama** [comment]
> ack, looks like success? https://github.com/cncf/sandbox/issues/93#issuecomment-2318560429

Yup, I think this is just for tracking. Safe to close?
