### ISSUE TITLE
APAC friendly meeting setup for tag-observability

### ISSUE THREAD

**Issue by ralf0131** [cncf/tag-observability#190]
As is mentioned #181 the APAC friendly tag-observability meeting has been proposed and we have successfully held the first meeting on July 9th (A google meeting was used instead of the zoom meeting).  

The issue was that the zoom meeting link requires user login to join the meeting, however due to the policy users from China cannot register any new user, which prevents users to join the meeting.

Therefore, we would like the infra team to setup a zoom meeting which does not require user login to join the meeting.

The reason I prefer the zoom meeting is because:
* it does not require a host to start the meeting
* the video can be automatically recorded and the recording can be accessible in public.

**Comment by krook** [comment]
Hi @ralf0131 

I've noticed that [Alolita had configured it to open without log in](https://github.com/cncf/tag-observability/issues/181#issuecomment-2218084746). 

I was also able to confirm that by going to the Zoom link in the [CNCF Community Calendar entry here](https://tockify.com/cncf.public.events/detail/750/1726012800000?search=Observability). 

If you still have an issue with that link, maybe @alolita can allow for unlogged in web browser based attendees?

**Comment by alolita** [comment]
Hi @krook The Zoom set up provisioned by the CNCF Service Desk request did not work as expected. We could not get the link to be used without login. This needs to be fixed since the setting for non-logged in users did not work for previous meetings.

**Comment by krook** [comment]
Thanks for the additional detail @alolita. I'll connect with @riaankleinhans to see what our options are for configuring that or providing a different Zoom account.

**Comment by riaankleinhans** [comment]
@ralf0131 they should be able to join without an LF account as guests
![image](https://github.com/user-attachments/assets/82ef38c5-1c40-48cc-a3c2-fb1cc2a25c66)

Which would require them to join using a name and email address, this is not a registration but just for idnetification in the meeting.
![image](https://github.com/user-attachments/assets/58947e8f-d75d-4472-8142-408976178bc6)

Please let me know if this option does not work in China, and some screenshots of the errors if possible.

**Comment by ralf0131** [comment]
@riaankleinhans  When I click the meeting link in https://tockify.com/cncf.public.events/detail/750/1726012800000?search=Observability , I still can't join with the following message:

![image](https://github.com/user-attachments/assets/eb9a20b6-a46d-4814-8214-54badcf64d0b)

As a reference, I just joined Java SIG (APAC friendly time) Wed, September 4, 18:00 – 19:00 [link](https://calendar.google.com/calendar/u/0/embed?src=c_2bf73e3b6b530da4babd444e72b76a6ad893a5c3f43cf40467abc7a9a897f977@group.calendar.google.com), and everything was good, I can join without logging.

> @ralf0131 they should be able to join without an LF account as guests 
> 
> Which would require them to join using a name and email address, this is not a registration but just for idnetification in the meeting. 

I didn't see this when I was trying to join the meeting. 

> Please let me know if this option does not work in China, and some screenshots of the errors if possible.

**Comment by ralf0131** [comment]
I also found something incorrect here in the calendar[1]. The correct meeting time should be:

6-7pm PT on the second Tuesday each month which is 9-10am (UTC+8 hours) on Wednesday.

[1] https://tockify.com/cncf.public.events/detail/750/1726012800000?search=Observability

**Comment by riaankleinhans** [comment]
@ralf0131 Thank you for the feedback.
The problem is that the meeting was a regular Zoom meeting, which require sign in.

- I have not moved the meeting to LFX, which does not require sign in, Just need to add your name with email and company being optional. - you can only test this 10min before the meeting next week.
- I also corrected the meeting time in the CNCF community calendar. - Please check if it is as expected, time zone mistakes happen.

**Comment by ralf0131** [comment]
@riaankleinhans Thanks for the update, now I can access the new meeting and it says I can join 10min before the meeting as you said. 
Since I cannot test it for now, I am not 100% sure I can join the meeting as expected...
Although I do not know how much work it will take, I think it will be great if the "no sign in" option can be turned on.

**Comment by riaankleinhans** [comment]
> @riaankleinhans Thanks for the update, now I can access the new meeting and it says I can join 10min before the meeting as you said. Since I cannot test it for now, I am not 100% sure I can join the meeting as expected... Although I do not know how much work it will take, I think it will be great if the "no sign in" option can be turned on.

Great, the APAC meeting will work for you with out signing in.

Up to the TAG leaders if they want to change the rest of the TAG meetings.
(TAG Security & App delivery already moved all their meetings)

**Comment by ralf0131** [comment]
Hi @riaankleinhans , Just want to make sure if the meeting will be recorded automatically or not?

**Comment by ralf0131** [comment]
@riaankleinhans Thanks for the help and we have successfully held the meeting! Could you please share the way to find the recordings, I searched for the CNCF [calendar](https://zoom-lfx.platform.linuxfoundation.org/meetings/cncf?view=week) but I could not find the recordings.

**Comment by riaankleinhans** [comment]
The meeting are in the [LFX calender](https://zoom-lfx.platform.linuxfoundation.org/meetings/cncf?view=week)
If you click on the meeting about an hour after the meeting, the meeting link would have changed into a [recording link](https://zoom.us/rec/share/biXc3eLh9jHkA-Wo0vvR-jaLgHr45o5X8CkbxWGY4aEgg0rP4EfMHfOmeax7zdIm.o_ZFr6tzAJewWyI6).

![image](https://github.com/user-attachments/assets/56fe3d0c-4f5f-479a-85b2-44a4365515f7)

The recording files can be downloaded from the zoom page by anyone, and uploaded to youtube, if that is way you work.
![image](https://github.com/user-attachments/assets/c38c43ce-9717-4253-a08c-0a7167bfcc8f)

Please let me know it you have more questions.

**Comment by riaankleinhans** [comment]
> > @riaankleinhans Thanks for the update, now I can access the new meeting and it says I can join 10min before the meeting as you said. Since I cannot test it for now, I am not 100% sure I can join the meeting as expected... Although I do not know how much work it will take, I think it will be great if the "no sign in" option can be turned on.
> 
> Great, the APAC meeting will work for you with out signing in.
> 
> Up to the TAG leaders if they want to change the rest of the TAG meetings. (TAG Security & App delivery already moved all their meetings)

@alolita let me know if the TAG would like to move all the TAG's meetings.
It is a bit of a effort on my side, but would work with leadership to make the process as smooth as possible.

**Comment by ralf0131** [comment]
@riaankleinhans @alolita Thanks I am able to view the recordings!
