### ISSUE TITLE
Update CNCF Calendar invites to include the new Google Docs link for meeting notes

### ISSUE THREAD

**Issue by halcyondude** [cncf/tag-observability#197]
We've moved our meeting notes to the CNCF shared google drive.  The new link is: 

https://docs.google.com/document/d/12mnMXQSrcS75eJS-5AGroX7xBpRPxhBlLzoYbXq49kk/edit?usp=sharing

**Comment by halcyondude** [comment]
Created new servicedesk ticket to update calendar invites: 

https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-2529

**Comment by alolita** [comment]
Thanks @halcyondude

**Comment by halcyondude** [comment]
calendar invites have been updated.
