### ISSUE TITLE
WG: State of Observability (survey)

### ISSUE THREAD

**Issue by halcyondude** [cncf/tag-observability#26]
The goal of this working group is to make an open community/collaborative approach to a survey of users to build a broader polling of users of open source observability solutions. This includes projects in the CNCF and projects outside of that community. 

The non-goals are executing how we distribute and what tools we use for the data collection. It could be anything from a simple Google Form to using a service like SurveyMonkey.

---

https://docs.google.com/document/d/1YPo6fJVTJ8pgqGPk7zdTA6aOtK5oNLg77ys8qdEsxMQ/edit#heading=h.wl6eks62d18g

**Comment by simskij** [comment]
This would be excellent to pick up again for 2022. I'm happy to contribute to making this happen.

**Comment by alolita** [comment]
Hi @simskij thanks for your interest. This survey would be valuable for TAG participants as well as observability stakeholders. Let's discuss what this survey would look like for 2022 at the next meeting you can join in to.

**Comment by alolita** [comment]
Closing this old issue. Let's open a new issue when we do the next survey.
