### ISSUE TITLE
Determine Meeting Timezone(s)

### ISSUE THREAD

**Issue by RichiH** [cncf/tag-observability#3]

**Comment by RichiH** [comment]
Started https://dudle.inf.tu-dresden.de/jrGTINFDmA/ as the first round. Let ML & Slack know

**Comment by dominick-blue** [comment]
@RichiH @halcyondude - is this something we still need to iron out? I see the last activity was Oct 2020. If so, can we move this onto the Kanban? Happy to relocate it and get it reprioritized for us if need be.

**Comment by alolita** [comment]
Closing this issue.

TAG Observability meeting time has been twice a month for the last two years now on the 1st and 3rd Tuesdays of each month. See https://github.com/cncf/tag-observability#how-we-communicate
