### ISSUE TITLE
DD for OpenMetrics

### ISSUE THREAD

**Issue by halcyondude** [cncf/tag-observability#30]

**Comment by RichiH** [comment]
As agreed in the last call, we updated our DD doc and replied to all comments old and new at the end of the one-week period. Also as agreed, I asked the mailing list to use the next week until the SIG call to read & reply so we can walk through the document smoothly.

**Comment by RichiH** [comment]
Cross-tracking: https://docs.google.com/document/d/1BN6ABvfbAMhJthH6xNOY5Lmls3jeE3kFbMgF04BzEKE/edit
