### ISSUE TITLE
s/sig/tag for charter

### ISSUE THREAD

**Issue by ianonavy** [cncf/tag-observability#44]
Context: https://github.com/cncf/toc/pull/654

Links are broken in the charter due to the rename of SIGs to TAGs. Also, the default branch in the TOC repo was changed from `master` to `main`.

FWIW @amye already made [these changes](https://github.com/cncf/toc/blob/81c3e43a2b90f44e00dda9f3f6750fdc381b6c4a/tags/observability.md) in the TOC repo; they would just need to back-ported here.

Happy to take a first stab if that's welcome! I understand if you don't want randos submitting PRs to your core document 😉

**Comment by halcyondude** [comment]
This is resolved by #46
