### ISSUE TITLE
[Observability Whitepaper] References missing and possible wrongly linked

### ISSUE THREAD

**Issue by wiardvanrij** [cncf/tag-observability#67]
For example

> "In control theory, observability is a measure of how well internal states of a system can be inferred from knowledge of its external outputs" [9]

Reference 9 is not present. 

Perhaps also it has to be double checked if references are actually correctly referenced. 

> Community research[4] conducted by ClearPath Strategies and Honeycomb.io

4 is:
> BEYER, Betsy; MURPHY, Niall; RENSIN, David; KAWAHARA, Kent; THORNE, Stephen. The Site Reliability Workbook. O'Reilly Media, 2018. Available at: https://sre.google/workbook/table-of-contents/. Accessed on: June 24, 2021.

I don't think (?) that this is the research by ClearPath and Honeycomb.

**Comment by bwplotka** [comment]
Ack, looking into it

**Comment by bwplotka** [comment]
Fixed in https://docs.google.com/document/d/19am_KCYWU28ebLiIXv_P3ji96edxCTscVb4CzemXV5A/edit, thanks! Will flow to main repo in a PR soon.
