### ISSUE TITLE
Contribute to adding profiling as OTEL supported event type

### ISSUE THREAD

**Issue by Rperry2174** [cncf/tag-observability#89]
As profiling has grown in popularity and more companies have started to build tooling around profiling, there has been a lot of discussion about [adding profiling as an official OTEL supported event type](https://github.com/open-telemetry/oteps/issues/139). 

Logs, metrics, and traces have already gone through a similar process to become more standardized and seeing as we have identified profiling as an "increasingly important" observability signal in [our whitepaper ](https://github.com/cncf/tag-observability/blob/main/whitepaper.md#profiles) it would be great for the observability tag to help provide input / resources towards this effort. 

Several interested groups from a profiling-developer slack channel, the OTEL issue linked above, and some who discussed this live at Kubecon EU this year have started to plan for making progress on this and I've compiled some general thoughts about possible next steps in a [doc here](https://docs.google.com/document/d/1iQ2s1NPkFXkOXkDg6RsMib_Q-akTLgyM2NZOJJBx6iE/edit?usp=sharing).

I'd love to discuss this as a group at the next meeting and also to gather thoughts, ideas, opinions, etc here as well!

**Comment by kenfinnigan** [comment]
Can this issue be considered "done" given profilings status in OTeL?

**Comment by halcyondude** [comment]
I think at this point yes :)

I DO think we should ideate (new issues / ideas heartily welcomed!) on how we maintain connection and alignment with the newly formed SIG Profiling, but the projects in-scope for the TAG generally, open-telemetry inclusive.
