### ISSUE TITLE
Draft proposal for initial set of Working Groups

### ISSUE THREAD

**Issue by halcyondude** [cncf/tag-observability#9]
_(from the [TOC TAG document](https://github.com/cncf/toc/blob/main/tags/cncf-tags.md#responsibilities--empowerment-of-tags))_

> TAGs may choose to spawn focussed and time-limited working groups to achieve some of their responsibilities (for example, to produce a specific educational white paper, or portfolio gap analysis report). Working groups should have a clearly documented charter, timeline (typically a few quarters at most), and set of deliverables. Once the timeline has elapsed, or the deliverables delivered, the working group dissolves, or is explicitly re-chartered.

We need a clear and approachable process for community members (and those that are considering joining) to propose and potentially form a new Working Group.  

To jumpstart and facilitate this:

- [x] Identify and Enumerate potential WG's (the [charter](https://github.com/cncf/tag-observability/blob/master/observability-charter.md) has a bunch to start with)
- [x] Propose a basic process we'll use to evaluate and create new WG's that's simple and clear
- [ ] Create an artifact (.md in this repo) that can be shared with community capturing this.

**Comment by rolfedh** [comment]
> > spawn focussed and time-limited working groups to achieve some of their responsibilities (for example, to produce a specific educational white paper, or portfolio gap analysis report). Working groups should have a clearly documented charter, timeline (typically a few quarters at most), and set of deliverables. Once the timeline has elapsed, or the deliverables delivered, the working group dissolves, or is explicitly re-chartered.
> 
> We need a clear and approachable process for community members (and those that are considering joining) to propose and potentially form a new Working Group.
> 
> To jumpstart and facilitate this:

I'd like to volunteer for this task.

**Comment by halcyondude** [comment]
Created https://github.com/cncf/tag-observability/projects/2  with phases:

Ideas --> Proposals --> Active --> Complete

**Comment by pbaderia01** [comment]
Hey @halcyondude! Since this issue was created before the SIG -> TAG transformation, the link for the TOC SIG document in the description is broken. Can you please update it to this: https://github.com/cncf/toc/blob/main/tags/cncf-tags.md#responsibilities--empowerment-of-tags

**Comment by pbaderia01** [comment]
A template for a proposal for a WG could look something like this: (each is a separate section)
**Description** : A short description of what the WG is all about.
**Impact** : The impact this WG will create.
**Scope** : A draft of the initial scope that the WG will be looking into (suggestions)
**WG Chairs/Leads Nominations (2/3)** : Even though the WG is open to everyone we need 2-3 people to lead the efforts.
**TAG Representative** : Someone from the TAG leadership team who will be coordinating all of these efforts and will help/guide wherever needed.
**Diversity/Inclusivity Moderator (Optional)** : Apart from the leadership team we should nominate a moderator who can review anything produced by the WG in any form and make sure it includes everyone.


Lifecycle of a proposal (We can create tags for this lifecycle and track the progress using the tags):
Proposal Created  **->**  Triage  **->**  WG Chairs Election  **->**  Finalisation Of Scope  **->**  Scope Presented at a TAG Meeting  **->**  Review Period (A week or till the next meeting to make sure everyone gets a chance to review the scope)  **->**  WIP  **->**  Review 
 **->**  Done  **->**  Next Steps 

This is just a draft template and once we have all the sections finalised we can create a template using this as the checklist.

**Comment by halcyondude** [comment]
This is a great start!  Let's get this into a PR so we get feedback from community and discuss there.

**Comment by halcyondude** [comment]
> Hey @halcyondude! Since this issue was created before the SIG -> TAG transformation, the link for the TOC SIG document in the description is broken. Can you please update it to this: https://github.com/cncf/toc/blob/main/tags/cncf-tags.md#responsibilities--empowerment-of-tags

done, thx

**Comment by halcyondude** [comment]
Here's a round-up of TAG issue templates we can draw from as well:

## Security
* https://github.com/cncf/tag-security/blob/main/.github/ISSUE_TEMPLATE/joint-review.md
* https://github.com/cncf/tag-security/blob/main/.github/ISSUE_TEMPLATE/presentation.md
* https://github.com/cncf/tag-security/blob/main/.github/ISSUE_TEMPLATE/proposal.md
* https://github.com/cncf/tag-security/blob/main/.github/ISSUE_TEMPLATE/suggestion.md

## Network
* https://github.com/cncf/tag-network/blob/master/.github/ISSUE_TEMPLATES/presentation.md
* https://github.com/cncf/tag-network/blob/master/.github/ISSUE_TEMPLATES/proposal.md
* https://github.com/cncf/tag-network/blob/master/.github/ISSUE_TEMPLATES/suggestion.md

I'll be adding some variation of these, a similar PR for the WG template would be great.

**Comment by pbaderia01** [comment]
> This is a great start! Let's get this into a PR so we get feedback from community and discuss there.

Done! A new template proposed here: #50

**Comment by dominick-blue** [comment]
@halcyondude @pbaderia01 - I see this was last actioned Jun 2021. Are we able to close this or relocate it to the Kanban? Happy to relocate it for us if need be. Just let me know.

**Comment by alolita** [comment]
This issue is dated and is now marked resolved.

As of June 2023, there are two active working groups under TAG Observability - 1) K8s Observe 2) [Observability Query Language Standardization](https://github.com/cncf/tag-observability/blob/main/working-groups/query-standardization.md)
